# Generated by Django 3.1 on 2020-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendreq', '0002_auto_20200827_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='isOpen',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='region',
            field=models.CharField(choices=[('Tel AVIV', 'Tel AVIV'), ('Jerusalem', 'Jerusalem')], default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='status',
            field=models.BooleanField(choices=[('open', 'open'), ('closed', 'closed')], default=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='item',
            field=models.CharField(choices=[('table', 'table'), ('bed', 'bed')], max_length=40),
        ),
    ]
