# Generated by Django 3.1 on 2020-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendreq', '0005_auto_20200831_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='special_req',
            field=models.TextField(),
        ),
    ]
