# Generated by Django 3.1 on 2020-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendreq', '0006_auto_20200831_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='special_req',
            field=models.CharField(max_length=400),
        ),
    ]
