name: Django CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install pipenv
        cd givitsite
        pipenv sync
       
        
    - name: DB creation
      run: |
        sudo apt install postgresql postgresql-contrib postgresql-common postgresql-client libpq-dev
        sudo systemctl start postgresql
        sudo -u postgres createdb givit 
        sudo -u postgres psql -c "ALTER ROLE postgres WITH PASSWORD 'givit';" 
        
    - name: migrate
      run: |
        cd givitsite
        pipenv run python3 manage.py migrate
